import { createHash } from 'node:crypto';
import { readdir, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const distDir = path.join(root, 'dist');

async function listFiles(directory, base = directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const absolute = path.join(directory, entry.name);

    if (entry.isDirectory()) {
      files.push(...(await listFiles(absolute, base)));
      continue;
    }

    const relative = path.relative(base, absolute).split(path.sep).join('/');

    if (relative === 'sw.js') {
      continue;
    }

    if (!/\.(?:js|css|html|ico|png|svg|jpg|jpeg|webp|woff2?|webmanifest)$/i.test(relative)) {
      continue;
    }

    files.push(`/${relative}`);
  }

  return files;
}

const assets = (await listFiles(distDir)).sort();
const version = createHash('sha1').update(assets.join('\n')).digest('hex').slice(0, 12);

const source = `/* Auto-generated by scripts/generate-sw.mjs — do not edit */
const CACHE_VERSION = ${JSON.stringify(version)};
const SHELL_CACHE = 'coffee-shell-' + CACHE_VERSION;
const PRECACHE_URLS = ${JSON.stringify(assets, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(SHELL_CACHE).then((cache) => cache.addAll(PRECACHE_URLS))
  );
  // Do not skipWaiting here — the app prompts via SKIP_WAITING to avoid mid-session corruption.
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys
          .filter((key) => key.startsWith('coffee-shell-') && key !== SHELL_CACHE)
          .map((key) => caches.delete(key))
      )
    ).then(() => self.clients.claim())
  );
});

function isAuthoritativeApi(url) {
  return url.pathname.startsWith('/api/')
    || url.pathname.startsWith('/sanctum/')
    || /\\/api\\/v\\d+\\//.test(url.pathname);
}

function isNavigationShell(url) {
  return url.pathname === '/'
    || url.pathname === '/index.html'
    || url.pathname.endsWith('/index.html');
}

function isNeverCachePath(url) {
  return url.pathname.endsWith('/sw.js')
    || url.pathname.endsWith('sw.js')
    || url.pathname.endsWith('.webmanifest')
    || url.pathname.endsWith('/manifest.webmanifest');
}

function isHashedAsset(url) {
  return url.pathname.startsWith('/assets/');
}

async function networkFirstNavigation(request) {
  try {
    const response = await fetch(request);

    if (response && response.ok) {
      const cache = await caches.open(SHELL_CACHE);
      await cache.put('/index.html', response.clone());
    }

    return response;
  } catch {
    return (await caches.match('/index.html'))
      || (await caches.match('/offline.html'))
      || Response.error();
  }
}

async function networkFirst(request) {
  try {
    return await fetch(request);
  } catch {
    return (await caches.match(request)) || Response.error();
  }
}

async function cacheFirstHashedAsset(request) {
  const cached = await caches.match(request);

  if (cached) {
    return cached;
  }

  const response = await fetch(request);

  if (!response || response.status !== 200 || response.type !== 'basic') {
    return response;
  }

  const contentType = response.headers.get('content-type') || '';

  // Never cache HTML (or other documents) as static assets — prevents MIME mistakes
  // when a host falls back unknown paths to index.html.
  if (contentType.includes('text/html') || contentType.includes('text/xml')) {
    return response;
  }

  const copy = response.clone();
  void caches.open(SHELL_CACHE).then((cache) => cache.put(request, copy));

  return response;
}

async function staleWhileRevalidate(request) {
  const cache = await caches.open(SHELL_CACHE);
  const cached = await cache.match(request);
  const networkPromise = fetch(request)
    .then((response) => {
      if (!response || response.status !== 200 || response.type !== 'basic') {
        return response;
      }

      const contentType = response.headers.get('content-type') || '';

      if (contentType.includes('text/html') || contentType.includes('text/xml')) {
        return response;
      }

      void cache.put(request, response.clone());

      return response;
    })
    .catch(() => null);

  return cached || (await networkPromise) || Response.error();
}

self.addEventListener('fetch', (event) => {
  const request = event.request;

  if (request.method !== 'GET') {
    return;
  }

  const url = new URL(request.url);

  if (url.origin !== self.location.origin) {
    return;
  }

  if (isAuthoritativeApi(url) || url.pathname.startsWith('/storage/')) {
    return;
  }

  if (isNeverCachePath(url)) {
    event.respondWith(networkFirst(request));
    return;
  }

  if (request.mode === 'navigate' || isNavigationShell(url)) {
    event.respondWith(networkFirstNavigation(request));
    return;
  }

  if (isHashedAsset(url)) {
    event.respondWith(cacheFirstHashedAsset(request));
    return;
  }

  event.respondWith(staleWhileRevalidate(request));
});

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
`;

await writeFile(path.join(distDir, 'sw.js'), source, 'utf8');
console.log(`Generated dist/sw.js (cache ${version}, ${assets.length} assets)`);
