import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const distDir = path.join(root, 'dist');

async function listFiles(directory, base = directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const files = [];

  for (const entry of entries) {
    const absolute = path.join(directory, entry.name);

    if (entry.isDirectory()) {
      files.push(...(await listFiles(absolute, base)));
      continue;
    }

    const relative = path.relative(base, absolute).split(path.sep).join('/');

    if (relative === 'sw.js') {
      continue;
    }

    if (!/\.(?:js|css|html|ico|png|svg|jpg|jpeg|webp|woff2?|webmanifest)$/i.test(relative)) {
      continue;
    }

    files.push(`/${relative}`);
  }

  return files;
}

const assets = (await listFiles(distDir)).sort();
const version = createHash('sha1').update(assets.join('\n')).digest('hex').slice(0, 12);

const source = `/* Auto-generated by scripts/generate-sw.mjs — do not edit */
const CACHE_VERSION = ${JSON.stringify(version)};
const SHELL_CACHE = 'coffee-shell-' + CACHE_VERSION;
const PRECACHE_URLS = ${JSON.stringify(assets, null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(SHELL_CACHE).then((cache) => cache.addAll(PRECACHE_URLS))
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys
          .filter((key) => key.startsWith('coffee-shell-') && key !== SHELL_CACHE)
          .map((key) => caches.delete(key))
      )
    ).then(() => self.clients.claim())
  );
});

function isAuthoritativeApi(url) {
  return url.pathname.startsWith('/api/') || url.pathname.startsWith('/sanctum/') || /\\/api\\/v\\d+\\//.test(url.pathname);
}

self.addEventListener('fetch', (event) => {
  const request = event.request;

  if (request.method !== 'GET') {
    return;
  }

  const url = new URL(request.url);

  if (url.origin !== self.location.origin) {
    if (isAuthoritativeApi(url)) {
      return;
    }

    return;
  }

  if (isAuthoritativeApi(url)) {
    return;
  }

  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          return response;
        })
        .catch(async () => {
          return (await caches.match('/index.html')) || (await caches.match('/offline.html')) || Response.error();
        })
    );
    return;
  }

  event.respondWith(
    caches.match(request).then((cached) => {
      if (cached) {
        return cached;
      }

      return fetch(request).then((response) => {
        if (!response || response.status !== 200 || response.type !== 'basic') {
          return response;
        }

        const copy = response.clone();
        void caches.open(SHELL_CACHE).then((cache) => cache.put(request, copy));
        return response;
      });
    })
  );
});

self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});
`;

await writeFile(path.join(distDir, 'sw.js'), source, 'utf8');
console.log(`Generated dist/sw.js (cache ${version}, ${assets.length} assets)`);
